### ISSUE TITLE
Add basic config management to store settings to user dir

### ISSUE THREAD

**Issue by pushfoo** [biskette/code-jam-6#1]
reasonable default homedir storage for:
- mac : `~/Library/Preferences/AncientTime`
- windows : `%localappdata%/Local/AncientTime`
- linux: `~/.AncientTime`

needs to store:
- api key
- lat/long

will use:
configparser

also, should default to searching immediate rundir first

**Comment by SharpBit** [comment]
for windows after AppData there should be either Local, LocalLow, or Roaming before the AncientTime folder
![image](https://user-images.githubusercontent.com/31069084/72686732-b782ea80-3ac5-11ea-878d-e6f9677df96e.png)

**Comment by pushfoo** [comment]
there seems to be a windows path var for that actually, %localappdata%

**Comment by pushfoo** [comment]
it turns out that the kivy App class has a user_data_dir attribute that's autofilled with a platform-specific data dir. Will try using that.

**Comment by pushfoo** [comment]
change of plans: config support is should go in the run directory for now as it's easier for the judges to use.

additionally, this ties into the UI since it's seemingly inescapable with kivy. Current version works for saving settings, but the refactor of the dial is not working out well rn.

**Comment by JakeHuneau** [comment]
Does `pathlib.Path.home()` suffice for this? I think that will find the home directory based on the OS, so we don't need to manually do that. I only have a mac, so I'm not sure if it works on windows the same way.

https://docs.python.org/3/library/pathlib.html#pathlib.Path.home

**Comment by pushfoo** [comment]
There's a way to handle it via an inbuilt constant + arguments to kivy's ConfigParser subclass. I agree that for a proper application that would be the way to go, but it's more judge-friendly to read from the run directory. That way if they feel like messing with the config file, they can do that.
